CREATE TABLE USERS (ID serial
                      UNIQUE,
                      EMAIL text, CREATED TIMESTAMP WITH TIME ZONE DEFAULT
                      CURRENT_TIMESTAMP,
                      UPDATED TIMESTAMP WITH TIME ZONE DEFAULT
                      CURRENT_TIMESTAMP,
                      SIGNED_IN TIMESTAMP WITH TIME ZONE);
  CREATE TABLE DOCUMENTS (ID serial, AUTHOR_ID integer REFERENCES USERS (ID), text text, CREATED TIMESTAMP WITH TIME ZONE DEFAULT
                            CURRENT_TIMESTAMP,
                            UPDATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);